mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('ads/', include('ads.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/shows/urls.py
from django.urls import path
from . import views


# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'shows'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.ShowCreate.as_view(), name='show_create'),
    path('main/<int:pk>/update/', views.ShowUpdate.as_view(), name='show_update'),
    path('main/<int:pk>/delete/', views.ShowDelete.as_view(), name='show_delete'),
    path('lookup/', views.GenreView.as_view(), name='genre_list'),
    path('lookup/create/', views.GenreCreate.as_view(), name='genre_create'),
    path('lookup/<int:pk>/update/', views.GenreUpdate.as_view(), name='genre_update'),
    path('lookup/<int:pk>/delete/', views.GenreDelete.as_view(), name='genre_delete'),
]

mysite/shows/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Genre(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Genre must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Show(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    minutes = models.PositiveIntegerField()
    summary = models.CharField(max_length=300)
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/shows/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from shows.models import Show, Genre



class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Genre.objects.all().count()
        al = Show.objects.all()

        ctx = {'genre_count': mc, 'show_list': al}
        return render(request, 'shows/show_list.html', ctx)


class GenreView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Genre.objects.all()
        ctx = {'genre_list': ml}
        return render(request, 'shows/genre_list.html', ctx)

#For Show
class ShowCreate(LoginRequiredMixin, CreateView):
    model = Show
    fields = '__all__'
    success_url = reverse_lazy('shows:all')


class ShowUpdate(LoginRequiredMixin, UpdateView):
    model = Show
    fields = '__all__'
    success_url = reverse_lazy('shows:all')


class ShowDelete(LoginRequiredMixin, DeleteView):
    model = Show
    fields = '__all__'
    success_url = reverse_lazy('shows:all')


#For Genre
class GenreCreate(LoginRequiredMixin, CreateView):
    model = Genre
    fields = '__all__'
    success_url = reverse_lazy('shows:all')


class GenreUpdate(LoginRequiredMixin, UpdateView):
    model = Genre
    fields = '__all__'
    success_url = reverse_lazy('shows:all')


class GenreDelete(LoginRequiredMixin, DeleteView):
    model = Genre
    fields = '__all__'
    success_url = reverse_lazy('shows:all')

mysite/shows/templates/shows/genre_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Genre</h1>

<p>Are you sure you want to delete the genre: {{ genre }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'shows:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/shows/templates/shows/genre_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'shows:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/shows/templates/shows/genre_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Genre List</h1>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
          {{ genre.name }}
         (<a href="{% url 'shows:genre_update' genre.id %}">Update</a> |
          <a href="{% url 'shows:genre_delete' genre.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no genres in the library.</p>
  {% endif %}
  <p><a href="{% url 'shows:genre_create' %}">Add a genre</a></p>
  <p>
    <a href="{% url 'shows:all' %}">Back to shows</a>
  </p>
{% endblock %}

mysite/shows/templates/shows/show_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Show</h1>

<p>Are you sure you want to delete the show: {{ show }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/shows/templates/shows/show_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'shows:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/shows/templates/shows/show_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Show List</h1>
  {% if show_list %}
  <ul>
    {% for show in show_list %}
      <li>
          {{ show.nickname }} ({{ show.genre }})
          (<a href="{% url 'shows:show_update' show.id %}">Update</a> |
          <a href="{% url 'shows:show_delete' show.id %}">Delete</a>) <br/>
          {{ show.minutes }} ({{ show.summary }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no shows in the library.</p>
  {% endif %}
  <p>
    {% if genre_count > 0 %}
      <a href="{% url 'shows:show_create' %}">Add a show</a>
    {% else %}
      Please add a genre before you add a show.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'shows:genre_list' %}">View genres</a> ({{ genre_count }}) |
    <a href="{% url 'shows:genre_create' %}">Add a genre</a>
  </p>
{% endblock %}